# docker-compose.yml

services:
    batch:
        container_name: batch
        build:
            context: ./batch
        env_file:
            - .env
        environment:
            - PYTHONPATH=/app:${PYTHONPATH:-}
            - TZ=Asia/Tokyo
        volumes:
            - ./batch:/app
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8103:8002"
        depends_on:
            - aurora
        networks:
            - app_network
        command: tail -f /dev/null

    aurora:
        container_name: aurora
        build:
            context: ./aurora
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - PGTZ=Asia/Tokyo
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - "8134:5432"
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    pg_data:
